export const SplashName = "Splash"
export const ChooseName = "Choose"
export const SignInName = "SignIn"
export const SignupName = "Signup"
export const WaitingName = "Wait"
export const CreateShopName = "Create Shop"
